### ISSUE TITLE
Using default config when running the container

### ISSUE THREAD

**Issue by tommyknows** [looselyrigorous/docker-rtorrent#3]
Hi,

I'm trying to use the default config with your docker image in a Kubernetes Deployment.
However, in the init-script, you copy the config and then `exit 0` (https://github.com/looselyrigorous/docker-rtorrent/blob/master/root/init#L9).

Is there a reason behind this? 
If not, would it be possible to change?

Thanks

**Comment by looselyrigorous** [comment]
Hello,

The reasoning was that you would run: `docker run --rm -v "$(pwd)/config:/config" looselyrigorous/rtorrent`, and have the container bootstrap configuration for you in the host `./config/` folder. This is mentioned in the README [file](https://github.com/looselyrigorous/docker-rtorrent#configuration).

It was meant so that you would first bootstrap a config, change it to your liking and then actually run the container. I'd like to preserve this behaviour, but it can be done without making the container forcibly exit if there's no user-set config file, which I assume is the behaviour you expect.

P.S: I never considered the possibility of kubernetizing this, but would be more than happy to accept a pull request with example configuration, if you make it work.

**Comment by tommyknows** [comment]
Yes, the behaviour i'd expect is that if you do not provide a config file, it will copy the default over and use that one.
If I wanted to get the default config, i could either check the container by `exec`ing into it, or checking the github repo.

Another option would be to have the config file already at `/config`, and if someone mounted their own config, it would just get "shadowed" 🙂 would make the copying unnecessary.

Regarding kubernetizing:
I would be happy to provide an example config, will have a look at it 🙂
I am currently running flood-UI in another container (in the same pod). Would you want to have that container in the example as well?
